# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d670f2a762c9ac6749547e795b52b126189be7a0a02618fc4b4108e5c5ca572f1b8d1d4dadb4bfc786b571456563bbf9b9f9aa02709be9d4a20ac584bf8b3a7a

test:
  secret_key_base: 16df44e02b177299a8f63ea3b2cc12116a952f8182b75293b57cd40522f214ee0fbb26117662a06b8056228dcee2e62ee3015126d2a09d814f9be7a177cf8808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
